package com.test.model.domain;

import lombok.Data;

import java.util.Date;

@Data
public class MtcAfterOrder {

    MtcAfterOrderDetail detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.AFTER_ORDER_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private Long afterOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.AFTER_ORDER_NUM
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String afterOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.SO_ORDER_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private Long soOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.SO_ORDER_NUM
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String soOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.SERVICE_TYPE_CODE
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String serviceTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ORDER_STATUS
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.MEMBER_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.MASTER_CONTACTOR
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String masterContactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.MASTER_MOBILE
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String masterMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.CONTACTOR
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String contactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.CONTACTOR_SEX
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private Boolean contactorSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.MOBILE
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.REGION_COUNTRY_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String regionCountryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.REGION_PROVICE_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String regionProviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.REGION_CITY_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String regionCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.REGION_DISTRICT_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String regionDistrictId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.REGION_ADDRESS
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String regionAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.CREATION_DATE
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.CREATED_BY
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.LAST_UPDATED_BY
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private Long lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.LAST_UPDATE_DATE
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ENABLE_FLAG
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private Boolean enableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.TENANT_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.OBJECT_VERSION_NUMBER
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private Long objectVersionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ATTRIBUTE1
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ATTRIBUTE2
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ATTRIBUTE3
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ATTRIBUTE4
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ATTRIBUTE5
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ATTRIBUTE6
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String attribute6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ATTRIBUTE7
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String attribute7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ATTRIBUTE8
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String attribute8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ATTRIBUTE9
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String attribute9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ATTRIBUTE10
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String attribute10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ATTRIBUTE11
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String attribute11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ATTRIBUTE12
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String attribute12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ATTRIBUTE13
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String attribute13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ATTRIBUTE14
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String attribute14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.ATTRIBUTE15
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String attribute15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order.AFTER_DESCRIPTIONS
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    private String afterDescriptions;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.AFTER_ORDER_ID
     *
     * @return the value of mtc_after_order.AFTER_ORDER_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public Long getAfterOrderId() {
        return afterOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.AFTER_ORDER_ID
     *
     * @param afterOrderId the value for mtc_after_order.AFTER_ORDER_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAfterOrderId(Long afterOrderId) {
        this.afterOrderId = afterOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.AFTER_ORDER_NUM
     *
     * @return the value of mtc_after_order.AFTER_ORDER_NUM
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAfterOrderNum() {
        return afterOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.AFTER_ORDER_NUM
     *
     * @param afterOrderNum the value for mtc_after_order.AFTER_ORDER_NUM
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAfterOrderNum(String afterOrderNum) {
        this.afterOrderNum = afterOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.SO_ORDER_ID
     *
     * @return the value of mtc_after_order.SO_ORDER_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public Long getSoOrderId() {
        return soOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.SO_ORDER_ID
     *
     * @param soOrderId the value for mtc_after_order.SO_ORDER_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setSoOrderId(Long soOrderId) {
        this.soOrderId = soOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.SO_ORDER_NUM
     *
     * @return the value of mtc_after_order.SO_ORDER_NUM
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getSoOrderNum() {
        return soOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.SO_ORDER_NUM
     *
     * @param soOrderNum the value for mtc_after_order.SO_ORDER_NUM
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setSoOrderNum(String soOrderNum) {
        this.soOrderNum = soOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.SERVICE_TYPE_CODE
     *
     * @return the value of mtc_after_order.SERVICE_TYPE_CODE
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getServiceTypeCode() {
        return serviceTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.SERVICE_TYPE_CODE
     *
     * @param serviceTypeCode the value for mtc_after_order.SERVICE_TYPE_CODE
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setServiceTypeCode(String serviceTypeCode) {
        this.serviceTypeCode = serviceTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ORDER_STATUS
     *
     * @return the value of mtc_after_order.ORDER_STATUS
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ORDER_STATUS
     *
     * @param orderStatus the value for mtc_after_order.ORDER_STATUS
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.MEMBER_ID
     *
     * @return the value of mtc_after_order.MEMBER_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.MEMBER_ID
     *
     * @param memberId the value for mtc_after_order.MEMBER_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.MASTER_CONTACTOR
     *
     * @return the value of mtc_after_order.MASTER_CONTACTOR
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getMasterContactor() {
        return masterContactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.MASTER_CONTACTOR
     *
     * @param masterContactor the value for mtc_after_order.MASTER_CONTACTOR
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setMasterContactor(String masterContactor) {
        this.masterContactor = masterContactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.MASTER_MOBILE
     *
     * @return the value of mtc_after_order.MASTER_MOBILE
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getMasterMobile() {
        return masterMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.MASTER_MOBILE
     *
     * @param masterMobile the value for mtc_after_order.MASTER_MOBILE
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setMasterMobile(String masterMobile) {
        this.masterMobile = masterMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.CONTACTOR
     *
     * @return the value of mtc_after_order.CONTACTOR
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getContactor() {
        return contactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.CONTACTOR
     *
     * @param contactor the value for mtc_after_order.CONTACTOR
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setContactor(String contactor) {
        this.contactor = contactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.CONTACTOR_SEX
     *
     * @return the value of mtc_after_order.CONTACTOR_SEX
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public Boolean getContactorSex() {
        return contactorSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.CONTACTOR_SEX
     *
     * @param contactorSex the value for mtc_after_order.CONTACTOR_SEX
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setContactorSex(Boolean contactorSex) {
        this.contactorSex = contactorSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.MOBILE
     *
     * @return the value of mtc_after_order.MOBILE
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.MOBILE
     *
     * @param mobile the value for mtc_after_order.MOBILE
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.REGION_COUNTRY_ID
     *
     * @return the value of mtc_after_order.REGION_COUNTRY_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getRegionCountryId() {
        return regionCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.REGION_COUNTRY_ID
     *
     * @param regionCountryId the value for mtc_after_order.REGION_COUNTRY_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setRegionCountryId(String regionCountryId) {
        this.regionCountryId = regionCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.REGION_PROVICE_ID
     *
     * @return the value of mtc_after_order.REGION_PROVICE_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getRegionProviceId() {
        return regionProviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.REGION_PROVICE_ID
     *
     * @param regionProviceId the value for mtc_after_order.REGION_PROVICE_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setRegionProviceId(String regionProviceId) {
        this.regionProviceId = regionProviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.REGION_CITY_ID
     *
     * @return the value of mtc_after_order.REGION_CITY_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getRegionCityId() {
        return regionCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.REGION_CITY_ID
     *
     * @param regionCityId the value for mtc_after_order.REGION_CITY_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setRegionCityId(String regionCityId) {
        this.regionCityId = regionCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.REGION_DISTRICT_ID
     *
     * @return the value of mtc_after_order.REGION_DISTRICT_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getRegionDistrictId() {
        return regionDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.REGION_DISTRICT_ID
     *
     * @param regionDistrictId the value for mtc_after_order.REGION_DISTRICT_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setRegionDistrictId(String regionDistrictId) {
        this.regionDistrictId = regionDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.REGION_ADDRESS
     *
     * @return the value of mtc_after_order.REGION_ADDRESS
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getRegionAddress() {
        return regionAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.REGION_ADDRESS
     *
     * @param regionAddress the value for mtc_after_order.REGION_ADDRESS
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setRegionAddress(String regionAddress) {
        this.regionAddress = regionAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.CREATION_DATE
     *
     * @return the value of mtc_after_order.CREATION_DATE
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.CREATION_DATE
     *
     * @param creationDate the value for mtc_after_order.CREATION_DATE
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.CREATED_BY
     *
     * @return the value of mtc_after_order.CREATED_BY
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.CREATED_BY
     *
     * @param createdBy the value for mtc_after_order.CREATED_BY
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.LAST_UPDATED_BY
     *
     * @return the value of mtc_after_order.LAST_UPDATED_BY
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for mtc_after_order.LAST_UPDATED_BY
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.LAST_UPDATE_DATE
     *
     * @return the value of mtc_after_order.LAST_UPDATE_DATE
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for mtc_after_order.LAST_UPDATE_DATE
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ENABLE_FLAG
     *
     * @return the value of mtc_after_order.ENABLE_FLAG
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public Boolean getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ENABLE_FLAG
     *
     * @param enableFlag the value for mtc_after_order.ENABLE_FLAG
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setEnableFlag(Boolean enableFlag) {
        this.enableFlag = enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.TENANT_ID
     *
     * @return the value of mtc_after_order.TENANT_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.TENANT_ID
     *
     * @param tenantId the value for mtc_after_order.TENANT_ID
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.OBJECT_VERSION_NUMBER
     *
     * @return the value of mtc_after_order.OBJECT_VERSION_NUMBER
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public Long getObjectVersionNumber() {
        return objectVersionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.OBJECT_VERSION_NUMBER
     *
     * @param objectVersionNumber the value for mtc_after_order.OBJECT_VERSION_NUMBER
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setObjectVersionNumber(Long objectVersionNumber) {
        this.objectVersionNumber = objectVersionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ATTRIBUTE1
     *
     * @return the value of mtc_after_order.ATTRIBUTE1
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ATTRIBUTE1
     *
     * @param attribute1 the value for mtc_after_order.ATTRIBUTE1
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ATTRIBUTE2
     *
     * @return the value of mtc_after_order.ATTRIBUTE2
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ATTRIBUTE2
     *
     * @param attribute2 the value for mtc_after_order.ATTRIBUTE2
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ATTRIBUTE3
     *
     * @return the value of mtc_after_order.ATTRIBUTE3
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ATTRIBUTE3
     *
     * @param attribute3 the value for mtc_after_order.ATTRIBUTE3
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ATTRIBUTE4
     *
     * @return the value of mtc_after_order.ATTRIBUTE4
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ATTRIBUTE4
     *
     * @param attribute4 the value for mtc_after_order.ATTRIBUTE4
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ATTRIBUTE5
     *
     * @return the value of mtc_after_order.ATTRIBUTE5
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ATTRIBUTE5
     *
     * @param attribute5 the value for mtc_after_order.ATTRIBUTE5
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ATTRIBUTE6
     *
     * @return the value of mtc_after_order.ATTRIBUTE6
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ATTRIBUTE6
     *
     * @param attribute6 the value for mtc_after_order.ATTRIBUTE6
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ATTRIBUTE7
     *
     * @return the value of mtc_after_order.ATTRIBUTE7
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAttribute7() {
        return attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ATTRIBUTE7
     *
     * @param attribute7 the value for mtc_after_order.ATTRIBUTE7
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAttribute7(String attribute7) {
        this.attribute7 = attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ATTRIBUTE8
     *
     * @return the value of mtc_after_order.ATTRIBUTE8
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAttribute8() {
        return attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ATTRIBUTE8
     *
     * @param attribute8 the value for mtc_after_order.ATTRIBUTE8
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAttribute8(String attribute8) {
        this.attribute8 = attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ATTRIBUTE9
     *
     * @return the value of mtc_after_order.ATTRIBUTE9
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAttribute9() {
        return attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ATTRIBUTE9
     *
     * @param attribute9 the value for mtc_after_order.ATTRIBUTE9
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAttribute9(String attribute9) {
        this.attribute9 = attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ATTRIBUTE10
     *
     * @return the value of mtc_after_order.ATTRIBUTE10
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAttribute10() {
        return attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ATTRIBUTE10
     *
     * @param attribute10 the value for mtc_after_order.ATTRIBUTE10
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAttribute10(String attribute10) {
        this.attribute10 = attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ATTRIBUTE11
     *
     * @return the value of mtc_after_order.ATTRIBUTE11
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAttribute11() {
        return attribute11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ATTRIBUTE11
     *
     * @param attribute11 the value for mtc_after_order.ATTRIBUTE11
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAttribute11(String attribute11) {
        this.attribute11 = attribute11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ATTRIBUTE12
     *
     * @return the value of mtc_after_order.ATTRIBUTE12
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAttribute12() {
        return attribute12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ATTRIBUTE12
     *
     * @param attribute12 the value for mtc_after_order.ATTRIBUTE12
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAttribute12(String attribute12) {
        this.attribute12 = attribute12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ATTRIBUTE13
     *
     * @return the value of mtc_after_order.ATTRIBUTE13
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAttribute13() {
        return attribute13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ATTRIBUTE13
     *
     * @param attribute13 the value for mtc_after_order.ATTRIBUTE13
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAttribute13(String attribute13) {
        this.attribute13 = attribute13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ATTRIBUTE14
     *
     * @return the value of mtc_after_order.ATTRIBUTE14
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAttribute14() {
        return attribute14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ATTRIBUTE14
     *
     * @param attribute14 the value for mtc_after_order.ATTRIBUTE14
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAttribute14(String attribute14) {
        this.attribute14 = attribute14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.ATTRIBUTE15
     *
     * @return the value of mtc_after_order.ATTRIBUTE15
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAttribute15() {
        return attribute15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.ATTRIBUTE15
     *
     * @param attribute15 the value for mtc_after_order.ATTRIBUTE15
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAttribute15(String attribute15) {
        this.attribute15 = attribute15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order.AFTER_DESCRIPTIONS
     *
     * @return the value of mtc_after_order.AFTER_DESCRIPTIONS
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public String getAfterDescriptions() {
        return afterDescriptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order.AFTER_DESCRIPTIONS
     *
     * @param afterDescriptions the value for mtc_after_order.AFTER_DESCRIPTIONS
     *
     * @mbggenerated Tue Jul 28 10:58:36 GMT+08:00 2020
     */
    public void setAfterDescriptions(String afterDescriptions) {
        this.afterDescriptions = afterDescriptions;
    }
}