package com.test.model.domain;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class MtcAfterOrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.AFTER_ORDER_DETAIL_ID
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private Long afterOrderDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.AFTER_ORDER_ID
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private Long afterOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.AFTER_ORDER_NUM
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String afterOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.GOOD_ID
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private Long goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.GOOD_NUM
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String goodNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.QUANTITY
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private BigDecimal quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.PRICE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.UNIT_CODE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String unitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.RESERVE_START_DATE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private Date reserveStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.RESERVE_END_DATE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private Date reserveEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.RESERVE_MINUTE_INTERVAL
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private BigDecimal reserveMinuteInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.CREATION_DATE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.CREATED_BY
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.LAST_UPDATED_BY
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private Long lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.ENABLE_FLAG
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private Boolean enableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.TENANT_ID
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.OBJECT_VERSION_NUMBER
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private Long objectVersionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.ATTRIBUTE1
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.ATTRIBUTE2
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.ATTRIBUTE3
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.ATTRIBUTE4
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.ATTRIBUTE5
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.ATTRIBUTE6
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String attribute6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.ATTRIBUTE7
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String attribute7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.ATTRIBUTE8
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String attribute8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.ATTRIBUTE9
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String attribute9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.ATTRIBUTE10
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String attribute10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.ATTRIBUTE11
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String attribute11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.ATTRIBUTE12
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String attribute12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.ATTRIBUTE13
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String attribute13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.ATTRIBUTE14
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String attribute14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_after_order_detail.ATTRIBUTE15
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    private String attribute15;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.AFTER_ORDER_DETAIL_ID
     *
     * @return the value of mtc_after_order_detail.AFTER_ORDER_DETAIL_ID
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public Long getAfterOrderDetailId() {
        return afterOrderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.AFTER_ORDER_DETAIL_ID
     *
     * @param afterOrderDetailId the value for mtc_after_order_detail.AFTER_ORDER_DETAIL_ID
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAfterOrderDetailId(Long afterOrderDetailId) {
        this.afterOrderDetailId = afterOrderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.AFTER_ORDER_ID
     *
     * @return the value of mtc_after_order_detail.AFTER_ORDER_ID
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public Long getAfterOrderId() {
        return afterOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.AFTER_ORDER_ID
     *
     * @param afterOrderId the value for mtc_after_order_detail.AFTER_ORDER_ID
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAfterOrderId(Long afterOrderId) {
        this.afterOrderId = afterOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.AFTER_ORDER_NUM
     *
     * @return the value of mtc_after_order_detail.AFTER_ORDER_NUM
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getAfterOrderNum() {
        return afterOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.AFTER_ORDER_NUM
     *
     * @param afterOrderNum the value for mtc_after_order_detail.AFTER_ORDER_NUM
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAfterOrderNum(String afterOrderNum) {
        this.afterOrderNum = afterOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.GOOD_ID
     *
     * @return the value of mtc_after_order_detail.GOOD_ID
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public Long getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.GOOD_ID
     *
     * @param goodId the value for mtc_after_order_detail.GOOD_ID
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setGoodId(Long goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.GOOD_NUM
     *
     * @return the value of mtc_after_order_detail.GOOD_NUM
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getGoodNum() {
        return goodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.GOOD_NUM
     *
     * @param goodNum the value for mtc_after_order_detail.GOOD_NUM
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setGoodNum(String goodNum) {
        this.goodNum = goodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.QUANTITY
     *
     * @return the value of mtc_after_order_detail.QUANTITY
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.QUANTITY
     *
     * @param quantity the value for mtc_after_order_detail.QUANTITY
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.PRICE
     *
     * @return the value of mtc_after_order_detail.PRICE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.PRICE
     *
     * @param price the value for mtc_after_order_detail.PRICE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.UNIT_CODE
     *
     * @return the value of mtc_after_order_detail.UNIT_CODE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.UNIT_CODE
     *
     * @param unitCode the value for mtc_after_order_detail.UNIT_CODE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.RESERVE_START_DATE
     *
     * @return the value of mtc_after_order_detail.RESERVE_START_DATE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public Date getReserveStartDate() {
        return reserveStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.RESERVE_START_DATE
     *
     * @param reserveStartDate the value for mtc_after_order_detail.RESERVE_START_DATE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setReserveStartDate(Date reserveStartDate) {
        this.reserveStartDate = reserveStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.RESERVE_END_DATE
     *
     * @return the value of mtc_after_order_detail.RESERVE_END_DATE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public Date getReserveEndDate() {
        return reserveEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.RESERVE_END_DATE
     *
     * @param reserveEndDate the value for mtc_after_order_detail.RESERVE_END_DATE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setReserveEndDate(Date reserveEndDate) {
        this.reserveEndDate = reserveEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.RESERVE_MINUTE_INTERVAL
     *
     * @return the value of mtc_after_order_detail.RESERVE_MINUTE_INTERVAL
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public BigDecimal getReserveMinuteInterval() {
        return reserveMinuteInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.RESERVE_MINUTE_INTERVAL
     *
     * @param reserveMinuteInterval the value for mtc_after_order_detail.RESERVE_MINUTE_INTERVAL
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setReserveMinuteInterval(BigDecimal reserveMinuteInterval) {
        this.reserveMinuteInterval = reserveMinuteInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.CREATION_DATE
     *
     * @return the value of mtc_after_order_detail.CREATION_DATE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.CREATION_DATE
     *
     * @param creationDate the value for mtc_after_order_detail.CREATION_DATE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.CREATED_BY
     *
     * @return the value of mtc_after_order_detail.CREATED_BY
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.CREATED_BY
     *
     * @param createdBy the value for mtc_after_order_detail.CREATED_BY
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.LAST_UPDATED_BY
     *
     * @return the value of mtc_after_order_detail.LAST_UPDATED_BY
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for mtc_after_order_detail.LAST_UPDATED_BY
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.LAST_UPDATE_DATE
     *
     * @return the value of mtc_after_order_detail.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for mtc_after_order_detail.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.ENABLE_FLAG
     *
     * @return the value of mtc_after_order_detail.ENABLE_FLAG
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public Boolean getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.ENABLE_FLAG
     *
     * @param enableFlag the value for mtc_after_order_detail.ENABLE_FLAG
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setEnableFlag(Boolean enableFlag) {
        this.enableFlag = enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.TENANT_ID
     *
     * @return the value of mtc_after_order_detail.TENANT_ID
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.TENANT_ID
     *
     * @param tenantId the value for mtc_after_order_detail.TENANT_ID
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.OBJECT_VERSION_NUMBER
     *
     * @return the value of mtc_after_order_detail.OBJECT_VERSION_NUMBER
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public Long getObjectVersionNumber() {
        return objectVersionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.OBJECT_VERSION_NUMBER
     *
     * @param objectVersionNumber the value for mtc_after_order_detail.OBJECT_VERSION_NUMBER
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setObjectVersionNumber(Long objectVersionNumber) {
        this.objectVersionNumber = objectVersionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.ATTRIBUTE1
     *
     * @return the value of mtc_after_order_detail.ATTRIBUTE1
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.ATTRIBUTE1
     *
     * @param attribute1 the value for mtc_after_order_detail.ATTRIBUTE1
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.ATTRIBUTE2
     *
     * @return the value of mtc_after_order_detail.ATTRIBUTE2
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.ATTRIBUTE2
     *
     * @param attribute2 the value for mtc_after_order_detail.ATTRIBUTE2
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.ATTRIBUTE3
     *
     * @return the value of mtc_after_order_detail.ATTRIBUTE3
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.ATTRIBUTE3
     *
     * @param attribute3 the value for mtc_after_order_detail.ATTRIBUTE3
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.ATTRIBUTE4
     *
     * @return the value of mtc_after_order_detail.ATTRIBUTE4
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.ATTRIBUTE4
     *
     * @param attribute4 the value for mtc_after_order_detail.ATTRIBUTE4
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.ATTRIBUTE5
     *
     * @return the value of mtc_after_order_detail.ATTRIBUTE5
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.ATTRIBUTE5
     *
     * @param attribute5 the value for mtc_after_order_detail.ATTRIBUTE5
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.ATTRIBUTE6
     *
     * @return the value of mtc_after_order_detail.ATTRIBUTE6
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.ATTRIBUTE6
     *
     * @param attribute6 the value for mtc_after_order_detail.ATTRIBUTE6
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.ATTRIBUTE7
     *
     * @return the value of mtc_after_order_detail.ATTRIBUTE7
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getAttribute7() {
        return attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.ATTRIBUTE7
     *
     * @param attribute7 the value for mtc_after_order_detail.ATTRIBUTE7
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAttribute7(String attribute7) {
        this.attribute7 = attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.ATTRIBUTE8
     *
     * @return the value of mtc_after_order_detail.ATTRIBUTE8
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getAttribute8() {
        return attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.ATTRIBUTE8
     *
     * @param attribute8 the value for mtc_after_order_detail.ATTRIBUTE8
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAttribute8(String attribute8) {
        this.attribute8 = attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.ATTRIBUTE9
     *
     * @return the value of mtc_after_order_detail.ATTRIBUTE9
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getAttribute9() {
        return attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.ATTRIBUTE9
     *
     * @param attribute9 the value for mtc_after_order_detail.ATTRIBUTE9
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAttribute9(String attribute9) {
        this.attribute9 = attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.ATTRIBUTE10
     *
     * @return the value of mtc_after_order_detail.ATTRIBUTE10
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getAttribute10() {
        return attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.ATTRIBUTE10
     *
     * @param attribute10 the value for mtc_after_order_detail.ATTRIBUTE10
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAttribute10(String attribute10) {
        this.attribute10 = attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.ATTRIBUTE11
     *
     * @return the value of mtc_after_order_detail.ATTRIBUTE11
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getAttribute11() {
        return attribute11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.ATTRIBUTE11
     *
     * @param attribute11 the value for mtc_after_order_detail.ATTRIBUTE11
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAttribute11(String attribute11) {
        this.attribute11 = attribute11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.ATTRIBUTE12
     *
     * @return the value of mtc_after_order_detail.ATTRIBUTE12
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getAttribute12() {
        return attribute12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.ATTRIBUTE12
     *
     * @param attribute12 the value for mtc_after_order_detail.ATTRIBUTE12
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAttribute12(String attribute12) {
        this.attribute12 = attribute12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.ATTRIBUTE13
     *
     * @return the value of mtc_after_order_detail.ATTRIBUTE13
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getAttribute13() {
        return attribute13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.ATTRIBUTE13
     *
     * @param attribute13 the value for mtc_after_order_detail.ATTRIBUTE13
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAttribute13(String attribute13) {
        this.attribute13 = attribute13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.ATTRIBUTE14
     *
     * @return the value of mtc_after_order_detail.ATTRIBUTE14
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getAttribute14() {
        return attribute14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.ATTRIBUTE14
     *
     * @param attribute14 the value for mtc_after_order_detail.ATTRIBUTE14
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAttribute14(String attribute14) {
        this.attribute14 = attribute14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_after_order_detail.ATTRIBUTE15
     *
     * @return the value of mtc_after_order_detail.ATTRIBUTE15
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public String getAttribute15() {
        return attribute15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_after_order_detail.ATTRIBUTE15
     *
     * @param attribute15 the value for mtc_after_order_detail.ATTRIBUTE15
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    public void setAttribute15(String attribute15) {
        this.attribute15 = attribute15;
    }
}