package com.test.model.domain;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class MtcGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.GOOD_ID
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private Long goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.GOOD_NUM
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String goodNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.GOOD_NAME
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String goodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.UNIT_CODE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String unitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.MODEL
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.PRICE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.QUANTITY
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private BigDecimal quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.GOOD_BARCODE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String goodBarcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.REMARK
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.PURCHASE_PRICE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private BigDecimal purchasePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.SELLING_PRICE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private BigDecimal sellingPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.CREATION_DATE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.CREATED_BY
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.LAST_UPDATED_BY
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private Long lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.ENABLE_FLAG
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private Boolean enableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.TENANT_ID
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.OBJECT_VERSION_NUMBER
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private Long objectVersionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.ATTRIBUTE1
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.ATTRIBUTE2
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.ATTRIBUTE3
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.ATTRIBUTE4
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.ATTRIBUTE5
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.ATTRIBUTE6
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String attribute6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.ATTRIBUTE7
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String attribute7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.ATTRIBUTE8
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String attribute8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.ATTRIBUTE9
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String attribute9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.ATTRIBUTE10
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String attribute10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.ATTRIBUTE11
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String attribute11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.ATTRIBUTE12
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String attribute12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.ATTRIBUTE13
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String attribute13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.ATTRIBUTE14
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String attribute14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_goods.ATTRIBUTE15
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    private String attribute15;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.GOOD_ID
     *
     * @return the value of mtc_goods.GOOD_ID
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public Long getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.GOOD_ID
     *
     * @param goodId the value for mtc_goods.GOOD_ID
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setGoodId(Long goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.GOOD_NUM
     *
     * @return the value of mtc_goods.GOOD_NUM
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getGoodNum() {
        return goodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.GOOD_NUM
     *
     * @param goodNum the value for mtc_goods.GOOD_NUM
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setGoodNum(String goodNum) {
        this.goodNum = goodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.GOOD_NAME
     *
     * @return the value of mtc_goods.GOOD_NAME
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getGoodName() {
        return goodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.GOOD_NAME
     *
     * @param goodName the value for mtc_goods.GOOD_NAME
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setGoodName(String goodName) {
        this.goodName = goodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.UNIT_CODE
     *
     * @return the value of mtc_goods.UNIT_CODE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.UNIT_CODE
     *
     * @param unitCode the value for mtc_goods.UNIT_CODE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.MODEL
     *
     * @return the value of mtc_goods.MODEL
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.MODEL
     *
     * @param model the value for mtc_goods.MODEL
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.PRICE
     *
     * @return the value of mtc_goods.PRICE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.PRICE
     *
     * @param price the value for mtc_goods.PRICE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.QUANTITY
     *
     * @return the value of mtc_goods.QUANTITY
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.QUANTITY
     *
     * @param quantity the value for mtc_goods.QUANTITY
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.GOOD_BARCODE
     *
     * @return the value of mtc_goods.GOOD_BARCODE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getGoodBarcode() {
        return goodBarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.GOOD_BARCODE
     *
     * @param goodBarcode the value for mtc_goods.GOOD_BARCODE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setGoodBarcode(String goodBarcode) {
        this.goodBarcode = goodBarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.REMARK
     *
     * @return the value of mtc_goods.REMARK
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.REMARK
     *
     * @param remark the value for mtc_goods.REMARK
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.PURCHASE_PRICE
     *
     * @return the value of mtc_goods.PURCHASE_PRICE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public BigDecimal getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.PURCHASE_PRICE
     *
     * @param purchasePrice the value for mtc_goods.PURCHASE_PRICE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setPurchasePrice(BigDecimal purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.SELLING_PRICE
     *
     * @return the value of mtc_goods.SELLING_PRICE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public BigDecimal getSellingPrice() {
        return sellingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.SELLING_PRICE
     *
     * @param sellingPrice the value for mtc_goods.SELLING_PRICE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setSellingPrice(BigDecimal sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.CREATION_DATE
     *
     * @return the value of mtc_goods.CREATION_DATE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.CREATION_DATE
     *
     * @param creationDate the value for mtc_goods.CREATION_DATE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.CREATED_BY
     *
     * @return the value of mtc_goods.CREATED_BY
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.CREATED_BY
     *
     * @param createdBy the value for mtc_goods.CREATED_BY
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.LAST_UPDATED_BY
     *
     * @return the value of mtc_goods.LAST_UPDATED_BY
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for mtc_goods.LAST_UPDATED_BY
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.LAST_UPDATE_DATE
     *
     * @return the value of mtc_goods.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for mtc_goods.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.ENABLE_FLAG
     *
     * @return the value of mtc_goods.ENABLE_FLAG
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public Boolean getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.ENABLE_FLAG
     *
     * @param enableFlag the value for mtc_goods.ENABLE_FLAG
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setEnableFlag(Boolean enableFlag) {
        this.enableFlag = enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.TENANT_ID
     *
     * @return the value of mtc_goods.TENANT_ID
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.TENANT_ID
     *
     * @param tenantId the value for mtc_goods.TENANT_ID
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.OBJECT_VERSION_NUMBER
     *
     * @return the value of mtc_goods.OBJECT_VERSION_NUMBER
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public Long getObjectVersionNumber() {
        return objectVersionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.OBJECT_VERSION_NUMBER
     *
     * @param objectVersionNumber the value for mtc_goods.OBJECT_VERSION_NUMBER
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setObjectVersionNumber(Long objectVersionNumber) {
        this.objectVersionNumber = objectVersionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.ATTRIBUTE1
     *
     * @return the value of mtc_goods.ATTRIBUTE1
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.ATTRIBUTE1
     *
     * @param attribute1 the value for mtc_goods.ATTRIBUTE1
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.ATTRIBUTE2
     *
     * @return the value of mtc_goods.ATTRIBUTE2
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.ATTRIBUTE2
     *
     * @param attribute2 the value for mtc_goods.ATTRIBUTE2
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.ATTRIBUTE3
     *
     * @return the value of mtc_goods.ATTRIBUTE3
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.ATTRIBUTE3
     *
     * @param attribute3 the value for mtc_goods.ATTRIBUTE3
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.ATTRIBUTE4
     *
     * @return the value of mtc_goods.ATTRIBUTE4
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.ATTRIBUTE4
     *
     * @param attribute4 the value for mtc_goods.ATTRIBUTE4
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.ATTRIBUTE5
     *
     * @return the value of mtc_goods.ATTRIBUTE5
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.ATTRIBUTE5
     *
     * @param attribute5 the value for mtc_goods.ATTRIBUTE5
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.ATTRIBUTE6
     *
     * @return the value of mtc_goods.ATTRIBUTE6
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.ATTRIBUTE6
     *
     * @param attribute6 the value for mtc_goods.ATTRIBUTE6
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.ATTRIBUTE7
     *
     * @return the value of mtc_goods.ATTRIBUTE7
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getAttribute7() {
        return attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.ATTRIBUTE7
     *
     * @param attribute7 the value for mtc_goods.ATTRIBUTE7
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setAttribute7(String attribute7) {
        this.attribute7 = attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.ATTRIBUTE8
     *
     * @return the value of mtc_goods.ATTRIBUTE8
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getAttribute8() {
        return attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.ATTRIBUTE8
     *
     * @param attribute8 the value for mtc_goods.ATTRIBUTE8
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setAttribute8(String attribute8) {
        this.attribute8 = attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.ATTRIBUTE9
     *
     * @return the value of mtc_goods.ATTRIBUTE9
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getAttribute9() {
        return attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.ATTRIBUTE9
     *
     * @param attribute9 the value for mtc_goods.ATTRIBUTE9
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setAttribute9(String attribute9) {
        this.attribute9 = attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.ATTRIBUTE10
     *
     * @return the value of mtc_goods.ATTRIBUTE10
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getAttribute10() {
        return attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.ATTRIBUTE10
     *
     * @param attribute10 the value for mtc_goods.ATTRIBUTE10
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setAttribute10(String attribute10) {
        this.attribute10 = attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.ATTRIBUTE11
     *
     * @return the value of mtc_goods.ATTRIBUTE11
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getAttribute11() {
        return attribute11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.ATTRIBUTE11
     *
     * @param attribute11 the value for mtc_goods.ATTRIBUTE11
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setAttribute11(String attribute11) {
        this.attribute11 = attribute11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.ATTRIBUTE12
     *
     * @return the value of mtc_goods.ATTRIBUTE12
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getAttribute12() {
        return attribute12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.ATTRIBUTE12
     *
     * @param attribute12 the value for mtc_goods.ATTRIBUTE12
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setAttribute12(String attribute12) {
        this.attribute12 = attribute12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.ATTRIBUTE13
     *
     * @return the value of mtc_goods.ATTRIBUTE13
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getAttribute13() {
        return attribute13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.ATTRIBUTE13
     *
     * @param attribute13 the value for mtc_goods.ATTRIBUTE13
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setAttribute13(String attribute13) {
        this.attribute13 = attribute13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.ATTRIBUTE14
     *
     * @return the value of mtc_goods.ATTRIBUTE14
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getAttribute14() {
        return attribute14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.ATTRIBUTE14
     *
     * @param attribute14 the value for mtc_goods.ATTRIBUTE14
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setAttribute14(String attribute14) {
        this.attribute14 = attribute14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_goods.ATTRIBUTE15
     *
     * @return the value of mtc_goods.ATTRIBUTE15
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public String getAttribute15() {
        return attribute15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_goods.ATTRIBUTE15
     *
     * @param attribute15 the value for mtc_goods.ATTRIBUTE15
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    public void setAttribute15(String attribute15) {
        this.attribute15 = attribute15;
    }
}