package com.test.model.domain;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class MtcSalesOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.SO_ORDER_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private Long soOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.SO_ORDER_NUM
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String soOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ORDER_DATE
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.CONTRACT
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String contract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.MOBILE
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.REGION_COUNTRY_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String regionCountryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.REGION_PROVICE_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String regionProviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.REGION_CITY_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String regionCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.REGION_DISTRICT_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String regionDistrictId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.REGION_ADDRESS
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String regionAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.AMOUNT
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ORDER_USER_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private Long orderUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.STORE_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.STORE_NUM
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String storeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.CUSTPOMERSERVICE_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private Long custpomerserviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.PAYING_DATE
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private Date payingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ORDER_REMARK
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String orderRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.CREATION_DATE
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.CREATED_BY
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.LAST_UPDATED_BY
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private Long lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ENABLE_FLAG
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private Boolean enableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.TENANT_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.OBJECT_VERSION_NUMBER
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private Long objectVersionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ATTRIBUTE1
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ATTRIBUTE2
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ATTRIBUTE3
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ATTRIBUTE4
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ATTRIBUTE5
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ATTRIBUTE6
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String attribute6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ATTRIBUTE7
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String attribute7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ATTRIBUTE8
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String attribute8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ATTRIBUTE9
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String attribute9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ATTRIBUTE10
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String attribute10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ATTRIBUTE11
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String attribute11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ATTRIBUTE12
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String attribute12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ATTRIBUTE13
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String attribute13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ATTRIBUTE14
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String attribute14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_sales_order.ATTRIBUTE15
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    private String attribute15;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.SO_ORDER_ID
     *
     * @return the value of mtc_sales_order.SO_ORDER_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public Long getSoOrderId() {
        return soOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.SO_ORDER_ID
     *
     * @param soOrderId the value for mtc_sales_order.SO_ORDER_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setSoOrderId(Long soOrderId) {
        this.soOrderId = soOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.SO_ORDER_NUM
     *
     * @return the value of mtc_sales_order.SO_ORDER_NUM
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getSoOrderNum() {
        return soOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.SO_ORDER_NUM
     *
     * @param soOrderNum the value for mtc_sales_order.SO_ORDER_NUM
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setSoOrderNum(String soOrderNum) {
        this.soOrderNum = soOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ORDER_DATE
     *
     * @return the value of mtc_sales_order.ORDER_DATE
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ORDER_DATE
     *
     * @param orderDate the value for mtc_sales_order.ORDER_DATE
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.CONTRACT
     *
     * @return the value of mtc_sales_order.CONTRACT
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getContract() {
        return contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.CONTRACT
     *
     * @param contract the value for mtc_sales_order.CONTRACT
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setContract(String contract) {
        this.contract = contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.MOBILE
     *
     * @return the value of mtc_sales_order.MOBILE
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.MOBILE
     *
     * @param mobile the value for mtc_sales_order.MOBILE
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.REGION_COUNTRY_ID
     *
     * @return the value of mtc_sales_order.REGION_COUNTRY_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getRegionCountryId() {
        return regionCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.REGION_COUNTRY_ID
     *
     * @param regionCountryId the value for mtc_sales_order.REGION_COUNTRY_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setRegionCountryId(String regionCountryId) {
        this.regionCountryId = regionCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.REGION_PROVICE_ID
     *
     * @return the value of mtc_sales_order.REGION_PROVICE_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getRegionProviceId() {
        return regionProviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.REGION_PROVICE_ID
     *
     * @param regionProviceId the value for mtc_sales_order.REGION_PROVICE_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setRegionProviceId(String regionProviceId) {
        this.regionProviceId = regionProviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.REGION_CITY_ID
     *
     * @return the value of mtc_sales_order.REGION_CITY_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getRegionCityId() {
        return regionCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.REGION_CITY_ID
     *
     * @param regionCityId the value for mtc_sales_order.REGION_CITY_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setRegionCityId(String regionCityId) {
        this.regionCityId = regionCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.REGION_DISTRICT_ID
     *
     * @return the value of mtc_sales_order.REGION_DISTRICT_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getRegionDistrictId() {
        return regionDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.REGION_DISTRICT_ID
     *
     * @param regionDistrictId the value for mtc_sales_order.REGION_DISTRICT_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setRegionDistrictId(String regionDistrictId) {
        this.regionDistrictId = regionDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.REGION_ADDRESS
     *
     * @return the value of mtc_sales_order.REGION_ADDRESS
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getRegionAddress() {
        return regionAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.REGION_ADDRESS
     *
     * @param regionAddress the value for mtc_sales_order.REGION_ADDRESS
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setRegionAddress(String regionAddress) {
        this.regionAddress = regionAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.AMOUNT
     *
     * @return the value of mtc_sales_order.AMOUNT
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.AMOUNT
     *
     * @param amount the value for mtc_sales_order.AMOUNT
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ORDER_USER_ID
     *
     * @return the value of mtc_sales_order.ORDER_USER_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public Long getOrderUserId() {
        return orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ORDER_USER_ID
     *
     * @param orderUserId the value for mtc_sales_order.ORDER_USER_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setOrderUserId(Long orderUserId) {
        this.orderUserId = orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.STORE_ID
     *
     * @return the value of mtc_sales_order.STORE_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.STORE_ID
     *
     * @param storeId the value for mtc_sales_order.STORE_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.STORE_NUM
     *
     * @return the value of mtc_sales_order.STORE_NUM
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getStoreNum() {
        return storeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.STORE_NUM
     *
     * @param storeNum the value for mtc_sales_order.STORE_NUM
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setStoreNum(String storeNum) {
        this.storeNum = storeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.CUSTPOMERSERVICE_ID
     *
     * @return the value of mtc_sales_order.CUSTPOMERSERVICE_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public Long getCustpomerserviceId() {
        return custpomerserviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.CUSTPOMERSERVICE_ID
     *
     * @param custpomerserviceId the value for mtc_sales_order.CUSTPOMERSERVICE_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setCustpomerserviceId(Long custpomerserviceId) {
        this.custpomerserviceId = custpomerserviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.PAYING_DATE
     *
     * @return the value of mtc_sales_order.PAYING_DATE
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public Date getPayingDate() {
        return payingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.PAYING_DATE
     *
     * @param payingDate the value for mtc_sales_order.PAYING_DATE
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setPayingDate(Date payingDate) {
        this.payingDate = payingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ORDER_REMARK
     *
     * @return the value of mtc_sales_order.ORDER_REMARK
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getOrderRemark() {
        return orderRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ORDER_REMARK
     *
     * @param orderRemark the value for mtc_sales_order.ORDER_REMARK
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setOrderRemark(String orderRemark) {
        this.orderRemark = orderRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.CREATION_DATE
     *
     * @return the value of mtc_sales_order.CREATION_DATE
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.CREATION_DATE
     *
     * @param creationDate the value for mtc_sales_order.CREATION_DATE
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.CREATED_BY
     *
     * @return the value of mtc_sales_order.CREATED_BY
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.CREATED_BY
     *
     * @param createdBy the value for mtc_sales_order.CREATED_BY
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.LAST_UPDATED_BY
     *
     * @return the value of mtc_sales_order.LAST_UPDATED_BY
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for mtc_sales_order.LAST_UPDATED_BY
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.LAST_UPDATE_DATE
     *
     * @return the value of mtc_sales_order.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for mtc_sales_order.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ENABLE_FLAG
     *
     * @return the value of mtc_sales_order.ENABLE_FLAG
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public Boolean getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ENABLE_FLAG
     *
     * @param enableFlag the value for mtc_sales_order.ENABLE_FLAG
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setEnableFlag(Boolean enableFlag) {
        this.enableFlag = enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.TENANT_ID
     *
     * @return the value of mtc_sales_order.TENANT_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.TENANT_ID
     *
     * @param tenantId the value for mtc_sales_order.TENANT_ID
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.OBJECT_VERSION_NUMBER
     *
     * @return the value of mtc_sales_order.OBJECT_VERSION_NUMBER
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public Long getObjectVersionNumber() {
        return objectVersionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.OBJECT_VERSION_NUMBER
     *
     * @param objectVersionNumber the value for mtc_sales_order.OBJECT_VERSION_NUMBER
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setObjectVersionNumber(Long objectVersionNumber) {
        this.objectVersionNumber = objectVersionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ATTRIBUTE1
     *
     * @return the value of mtc_sales_order.ATTRIBUTE1
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ATTRIBUTE1
     *
     * @param attribute1 the value for mtc_sales_order.ATTRIBUTE1
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ATTRIBUTE2
     *
     * @return the value of mtc_sales_order.ATTRIBUTE2
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ATTRIBUTE2
     *
     * @param attribute2 the value for mtc_sales_order.ATTRIBUTE2
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ATTRIBUTE3
     *
     * @return the value of mtc_sales_order.ATTRIBUTE3
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ATTRIBUTE3
     *
     * @param attribute3 the value for mtc_sales_order.ATTRIBUTE3
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ATTRIBUTE4
     *
     * @return the value of mtc_sales_order.ATTRIBUTE4
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ATTRIBUTE4
     *
     * @param attribute4 the value for mtc_sales_order.ATTRIBUTE4
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ATTRIBUTE5
     *
     * @return the value of mtc_sales_order.ATTRIBUTE5
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ATTRIBUTE5
     *
     * @param attribute5 the value for mtc_sales_order.ATTRIBUTE5
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ATTRIBUTE6
     *
     * @return the value of mtc_sales_order.ATTRIBUTE6
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ATTRIBUTE6
     *
     * @param attribute6 the value for mtc_sales_order.ATTRIBUTE6
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ATTRIBUTE7
     *
     * @return the value of mtc_sales_order.ATTRIBUTE7
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getAttribute7() {
        return attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ATTRIBUTE7
     *
     * @param attribute7 the value for mtc_sales_order.ATTRIBUTE7
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setAttribute7(String attribute7) {
        this.attribute7 = attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ATTRIBUTE8
     *
     * @return the value of mtc_sales_order.ATTRIBUTE8
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getAttribute8() {
        return attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ATTRIBUTE8
     *
     * @param attribute8 the value for mtc_sales_order.ATTRIBUTE8
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setAttribute8(String attribute8) {
        this.attribute8 = attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ATTRIBUTE9
     *
     * @return the value of mtc_sales_order.ATTRIBUTE9
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getAttribute9() {
        return attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ATTRIBUTE9
     *
     * @param attribute9 the value for mtc_sales_order.ATTRIBUTE9
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setAttribute9(String attribute9) {
        this.attribute9 = attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ATTRIBUTE10
     *
     * @return the value of mtc_sales_order.ATTRIBUTE10
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getAttribute10() {
        return attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ATTRIBUTE10
     *
     * @param attribute10 the value for mtc_sales_order.ATTRIBUTE10
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setAttribute10(String attribute10) {
        this.attribute10 = attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ATTRIBUTE11
     *
     * @return the value of mtc_sales_order.ATTRIBUTE11
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getAttribute11() {
        return attribute11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ATTRIBUTE11
     *
     * @param attribute11 the value for mtc_sales_order.ATTRIBUTE11
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setAttribute11(String attribute11) {
        this.attribute11 = attribute11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ATTRIBUTE12
     *
     * @return the value of mtc_sales_order.ATTRIBUTE12
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getAttribute12() {
        return attribute12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ATTRIBUTE12
     *
     * @param attribute12 the value for mtc_sales_order.ATTRIBUTE12
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setAttribute12(String attribute12) {
        this.attribute12 = attribute12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ATTRIBUTE13
     *
     * @return the value of mtc_sales_order.ATTRIBUTE13
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getAttribute13() {
        return attribute13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ATTRIBUTE13
     *
     * @param attribute13 the value for mtc_sales_order.ATTRIBUTE13
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setAttribute13(String attribute13) {
        this.attribute13 = attribute13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ATTRIBUTE14
     *
     * @return the value of mtc_sales_order.ATTRIBUTE14
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getAttribute14() {
        return attribute14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ATTRIBUTE14
     *
     * @param attribute14 the value for mtc_sales_order.ATTRIBUTE14
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setAttribute14(String attribute14) {
        this.attribute14 = attribute14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_sales_order.ATTRIBUTE15
     *
     * @return the value of mtc_sales_order.ATTRIBUTE15
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public String getAttribute15() {
        return attribute15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_sales_order.ATTRIBUTE15
     *
     * @param attribute15 the value for mtc_sales_order.ATTRIBUTE15
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    public void setAttribute15(String attribute15) {
        this.attribute15 = attribute15;
    }
}