package com.test.model.domain;

import java.util.Date;

public class MtcWxClient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.WX_CLIENT_ID
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private Long wxClientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.WX_NICKNAME
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String wxNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.WX_URL
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String wxUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.WX_MOBILE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private Long wxMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.WX_TOKEN
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String wxToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.WX_OPENID
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String wxOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.WX_SEX
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private Boolean wxSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.WX_PROVINCE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String wxProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.WX_CITY
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String wxCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.WX_COUNTRY
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String wxCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.WX_PRIVILEGE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String wxPrivilege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.WX_UNIONID
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private Long wxUnionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.WX_APPID
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private Long wxAppid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.WX_SCOPE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String wxScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.CREATION_DATE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.CREATED_BY
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.LAST_UPDATED_BY
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private Long lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.ENABLE_FLAG
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private Boolean enableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.TENANT_ID
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.OBJECT_VERSION_NUMBER
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private Long objectVersionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.ATTRIBUTE1
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.ATTRIBUTE2
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.ATTRIBUTE3
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.ATTRIBUTE4
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.ATTRIBUTE5
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.ATTRIBUTE6
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String attribute6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.ATTRIBUTE7
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String attribute7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.ATTRIBUTE8
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String attribute8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.ATTRIBUTE9
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String attribute9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.ATTRIBUTE10
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String attribute10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.ATTRIBUTE11
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String attribute11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.ATTRIBUTE12
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String attribute12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.ATTRIBUTE13
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String attribute13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.ATTRIBUTE14
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String attribute14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtc_wx_client.ATTRIBUTE15
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    private String attribute15;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.WX_CLIENT_ID
     *
     * @return the value of mtc_wx_client.WX_CLIENT_ID
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public Long getWxClientId() {
        return wxClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.WX_CLIENT_ID
     *
     * @param wxClientId the value for mtc_wx_client.WX_CLIENT_ID
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setWxClientId(Long wxClientId) {
        this.wxClientId = wxClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.WX_NICKNAME
     *
     * @return the value of mtc_wx_client.WX_NICKNAME
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getWxNickname() {
        return wxNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.WX_NICKNAME
     *
     * @param wxNickname the value for mtc_wx_client.WX_NICKNAME
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setWxNickname(String wxNickname) {
        this.wxNickname = wxNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.WX_URL
     *
     * @return the value of mtc_wx_client.WX_URL
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getWxUrl() {
        return wxUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.WX_URL
     *
     * @param wxUrl the value for mtc_wx_client.WX_URL
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setWxUrl(String wxUrl) {
        this.wxUrl = wxUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.WX_MOBILE
     *
     * @return the value of mtc_wx_client.WX_MOBILE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public Long getWxMobile() {
        return wxMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.WX_MOBILE
     *
     * @param wxMobile the value for mtc_wx_client.WX_MOBILE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setWxMobile(Long wxMobile) {
        this.wxMobile = wxMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.WX_TOKEN
     *
     * @return the value of mtc_wx_client.WX_TOKEN
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getWxToken() {
        return wxToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.WX_TOKEN
     *
     * @param wxToken the value for mtc_wx_client.WX_TOKEN
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setWxToken(String wxToken) {
        this.wxToken = wxToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.WX_OPENID
     *
     * @return the value of mtc_wx_client.WX_OPENID
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.WX_OPENID
     *
     * @param wxOpenid the value for mtc_wx_client.WX_OPENID
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.WX_SEX
     *
     * @return the value of mtc_wx_client.WX_SEX
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public Boolean getWxSex() {
        return wxSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.WX_SEX
     *
     * @param wxSex the value for mtc_wx_client.WX_SEX
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setWxSex(Boolean wxSex) {
        this.wxSex = wxSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.WX_PROVINCE
     *
     * @return the value of mtc_wx_client.WX_PROVINCE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getWxProvince() {
        return wxProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.WX_PROVINCE
     *
     * @param wxProvince the value for mtc_wx_client.WX_PROVINCE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setWxProvince(String wxProvince) {
        this.wxProvince = wxProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.WX_CITY
     *
     * @return the value of mtc_wx_client.WX_CITY
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getWxCity() {
        return wxCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.WX_CITY
     *
     * @param wxCity the value for mtc_wx_client.WX_CITY
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setWxCity(String wxCity) {
        this.wxCity = wxCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.WX_COUNTRY
     *
     * @return the value of mtc_wx_client.WX_COUNTRY
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getWxCountry() {
        return wxCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.WX_COUNTRY
     *
     * @param wxCountry the value for mtc_wx_client.WX_COUNTRY
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setWxCountry(String wxCountry) {
        this.wxCountry = wxCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.WX_PRIVILEGE
     *
     * @return the value of mtc_wx_client.WX_PRIVILEGE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getWxPrivilege() {
        return wxPrivilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.WX_PRIVILEGE
     *
     * @param wxPrivilege the value for mtc_wx_client.WX_PRIVILEGE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setWxPrivilege(String wxPrivilege) {
        this.wxPrivilege = wxPrivilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.WX_UNIONID
     *
     * @return the value of mtc_wx_client.WX_UNIONID
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public Long getWxUnionid() {
        return wxUnionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.WX_UNIONID
     *
     * @param wxUnionid the value for mtc_wx_client.WX_UNIONID
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setWxUnionid(Long wxUnionid) {
        this.wxUnionid = wxUnionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.WX_APPID
     *
     * @return the value of mtc_wx_client.WX_APPID
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public Long getWxAppid() {
        return wxAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.WX_APPID
     *
     * @param wxAppid the value for mtc_wx_client.WX_APPID
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setWxAppid(Long wxAppid) {
        this.wxAppid = wxAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.WX_SCOPE
     *
     * @return the value of mtc_wx_client.WX_SCOPE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getWxScope() {
        return wxScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.WX_SCOPE
     *
     * @param wxScope the value for mtc_wx_client.WX_SCOPE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setWxScope(String wxScope) {
        this.wxScope = wxScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.CREATION_DATE
     *
     * @return the value of mtc_wx_client.CREATION_DATE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.CREATION_DATE
     *
     * @param creationDate the value for mtc_wx_client.CREATION_DATE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.CREATED_BY
     *
     * @return the value of mtc_wx_client.CREATED_BY
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.CREATED_BY
     *
     * @param createdBy the value for mtc_wx_client.CREATED_BY
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.LAST_UPDATED_BY
     *
     * @return the value of mtc_wx_client.LAST_UPDATED_BY
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for mtc_wx_client.LAST_UPDATED_BY
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.LAST_UPDATE_DATE
     *
     * @return the value of mtc_wx_client.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for mtc_wx_client.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.ENABLE_FLAG
     *
     * @return the value of mtc_wx_client.ENABLE_FLAG
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public Boolean getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.ENABLE_FLAG
     *
     * @param enableFlag the value for mtc_wx_client.ENABLE_FLAG
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setEnableFlag(Boolean enableFlag) {
        this.enableFlag = enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.TENANT_ID
     *
     * @return the value of mtc_wx_client.TENANT_ID
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.TENANT_ID
     *
     * @param tenantId the value for mtc_wx_client.TENANT_ID
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.OBJECT_VERSION_NUMBER
     *
     * @return the value of mtc_wx_client.OBJECT_VERSION_NUMBER
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public Long getObjectVersionNumber() {
        return objectVersionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.OBJECT_VERSION_NUMBER
     *
     * @param objectVersionNumber the value for mtc_wx_client.OBJECT_VERSION_NUMBER
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setObjectVersionNumber(Long objectVersionNumber) {
        this.objectVersionNumber = objectVersionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.ATTRIBUTE1
     *
     * @return the value of mtc_wx_client.ATTRIBUTE1
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.ATTRIBUTE1
     *
     * @param attribute1 the value for mtc_wx_client.ATTRIBUTE1
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.ATTRIBUTE2
     *
     * @return the value of mtc_wx_client.ATTRIBUTE2
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.ATTRIBUTE2
     *
     * @param attribute2 the value for mtc_wx_client.ATTRIBUTE2
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.ATTRIBUTE3
     *
     * @return the value of mtc_wx_client.ATTRIBUTE3
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.ATTRIBUTE3
     *
     * @param attribute3 the value for mtc_wx_client.ATTRIBUTE3
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.ATTRIBUTE4
     *
     * @return the value of mtc_wx_client.ATTRIBUTE4
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.ATTRIBUTE4
     *
     * @param attribute4 the value for mtc_wx_client.ATTRIBUTE4
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.ATTRIBUTE5
     *
     * @return the value of mtc_wx_client.ATTRIBUTE5
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.ATTRIBUTE5
     *
     * @param attribute5 the value for mtc_wx_client.ATTRIBUTE5
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.ATTRIBUTE6
     *
     * @return the value of mtc_wx_client.ATTRIBUTE6
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.ATTRIBUTE6
     *
     * @param attribute6 the value for mtc_wx_client.ATTRIBUTE6
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.ATTRIBUTE7
     *
     * @return the value of mtc_wx_client.ATTRIBUTE7
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getAttribute7() {
        return attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.ATTRIBUTE7
     *
     * @param attribute7 the value for mtc_wx_client.ATTRIBUTE7
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setAttribute7(String attribute7) {
        this.attribute7 = attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.ATTRIBUTE8
     *
     * @return the value of mtc_wx_client.ATTRIBUTE8
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getAttribute8() {
        return attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.ATTRIBUTE8
     *
     * @param attribute8 the value for mtc_wx_client.ATTRIBUTE8
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setAttribute8(String attribute8) {
        this.attribute8 = attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.ATTRIBUTE9
     *
     * @return the value of mtc_wx_client.ATTRIBUTE9
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getAttribute9() {
        return attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.ATTRIBUTE9
     *
     * @param attribute9 the value for mtc_wx_client.ATTRIBUTE9
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setAttribute9(String attribute9) {
        this.attribute9 = attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.ATTRIBUTE10
     *
     * @return the value of mtc_wx_client.ATTRIBUTE10
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getAttribute10() {
        return attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.ATTRIBUTE10
     *
     * @param attribute10 the value for mtc_wx_client.ATTRIBUTE10
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setAttribute10(String attribute10) {
        this.attribute10 = attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.ATTRIBUTE11
     *
     * @return the value of mtc_wx_client.ATTRIBUTE11
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getAttribute11() {
        return attribute11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.ATTRIBUTE11
     *
     * @param attribute11 the value for mtc_wx_client.ATTRIBUTE11
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setAttribute11(String attribute11) {
        this.attribute11 = attribute11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.ATTRIBUTE12
     *
     * @return the value of mtc_wx_client.ATTRIBUTE12
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getAttribute12() {
        return attribute12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.ATTRIBUTE12
     *
     * @param attribute12 the value for mtc_wx_client.ATTRIBUTE12
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setAttribute12(String attribute12) {
        this.attribute12 = attribute12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.ATTRIBUTE13
     *
     * @return the value of mtc_wx_client.ATTRIBUTE13
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getAttribute13() {
        return attribute13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.ATTRIBUTE13
     *
     * @param attribute13 the value for mtc_wx_client.ATTRIBUTE13
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setAttribute13(String attribute13) {
        this.attribute13 = attribute13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.ATTRIBUTE14
     *
     * @return the value of mtc_wx_client.ATTRIBUTE14
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getAttribute14() {
        return attribute14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.ATTRIBUTE14
     *
     * @param attribute14 the value for mtc_wx_client.ATTRIBUTE14
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setAttribute14(String attribute14) {
        this.attribute14 = attribute14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtc_wx_client.ATTRIBUTE15
     *
     * @return the value of mtc_wx_client.ATTRIBUTE15
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public String getAttribute15() {
        return attribute15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtc_wx_client.ATTRIBUTE15
     *
     * @param attribute15 the value for mtc_wx_client.ATTRIBUTE15
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    public void setAttribute15(String attribute15) {
        this.attribute15 = attribute15;
    }
}