package com.test.model.persistence;

import com.test.model.domain.MtcAfterOrderDetail;
import com.test.model.domain.MtcAfterOrderDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MtcAfterOrderDetailMapper {

    List<MtcAfterOrderDetail> getDetail(@Param(value = "afterOrderId") long afterOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_after_order_detail
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    int countByExample(MtcAfterOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_after_order_detail
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    int deleteByExample(MtcAfterOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_after_order_detail
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long afterOrderDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_after_order_detail
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    int insert(MtcAfterOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_after_order_detail
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    int insertSelective(MtcAfterOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_after_order_detail
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    List<MtcAfterOrderDetail> selectByExample(MtcAfterOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_after_order_detail
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    MtcAfterOrderDetail selectByPrimaryKey(Long afterOrderDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_after_order_detail
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") MtcAfterOrderDetail record, @Param("example") MtcAfterOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_after_order_detail
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    int updateByExample(@Param("record") MtcAfterOrderDetail record, @Param("example") MtcAfterOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_after_order_detail
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(MtcAfterOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_after_order_detail
     *
     * @mbggenerated Mon Jul 27 19:33:16 GMT+08:00 2020
     */
    int updateByPrimaryKey(MtcAfterOrderDetail record);
}