package com.test.model.persistence;

import com.test.model.domain.MtcGoods;
import com.test.model.domain.MtcGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface MtcGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_goods
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    int countByExample(MtcGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_goods
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    int deleteByExample(MtcGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_goods
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long goodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_goods
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    int insert(MtcGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_goods
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    int insertSelective(MtcGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_goods
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    List<MtcGoods> selectByExample(MtcGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_goods
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    MtcGoods selectByPrimaryKey(Long goodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_goods
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") MtcGoods record, @Param("example") MtcGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_goods
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    int updateByExample(@Param("record") MtcGoods record, @Param("example") MtcGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_goods
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(MtcGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_goods
     *
     * @mbggenerated Mon Jul 27 10:06:57 GMT+08:00 2020
     */
    int updateByPrimaryKey(MtcGoods record);
}