package com.test.model.persistence;

import com.test.model.domain.MtcSalesOrder;
import com.test.model.domain.MtcSalesOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface MtcSalesOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_sales_order
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    int countByExample(MtcSalesOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_sales_order
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    int deleteByExample(MtcSalesOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_sales_order
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long soOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_sales_order
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    int insert(MtcSalesOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_sales_order
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    int insertSelective(MtcSalesOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_sales_order
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    List<MtcSalesOrder> selectByExample(MtcSalesOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_sales_order
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    MtcSalesOrder selectByPrimaryKey(Long soOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_sales_order
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") MtcSalesOrder record, @Param("example") MtcSalesOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_sales_order
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    int updateByExample(@Param("record") MtcSalesOrder record, @Param("example") MtcSalesOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_sales_order
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(MtcSalesOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_sales_order
     *
     * @mbggenerated Mon Jul 27 10:52:08 GMT+08:00 2020
     */
    int updateByPrimaryKey(MtcSalesOrder record);
}