package com.test.model.persistence;

import com.test.model.domain.MtcWxClient;
import com.test.model.domain.MtcWxClientExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MtcWxClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_wx_client
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    int countByExample(MtcWxClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_wx_client
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    int deleteByExample(MtcWxClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_wx_client
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long wxClientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_wx_client
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    int insert(MtcWxClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_wx_client
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    int insertSelective(MtcWxClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_wx_client
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    List<MtcWxClient> selectByExample(MtcWxClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_wx_client
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    MtcWxClient selectByPrimaryKey(Long wxClientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_wx_client
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") MtcWxClient record, @Param("example") MtcWxClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_wx_client
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    int updateByExample(@Param("record") MtcWxClient record, @Param("example") MtcWxClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_wx_client
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(MtcWxClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtc_wx_client
     *
     * @mbggenerated Mon Jul 27 12:42:11 GMT+08:00 2020
     */
    int updateByPrimaryKey(MtcWxClient record);
}